name: Build
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4.1.1
    - name: Apply execute permissions on setup.sh
      run: chmod +x setup.sh
    - name: Setup project
      run: ./setup.sh
    - name: Build project
      run: make
    - uses: actions/upload-artifact@v4.1.0
      with:
        name: PWC
        path: PWC

